name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./mvnw package && java -jar target/gs-spring-boot-docker-0.1.0.jar
      working-directory: target
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: vinaydevops
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar
